// AUTO-GENERATED by scripts/generate-feature-registry.js — DO NOT EDIT BY HAND.
// Run `npm run generate:features` to regenerate.
// On a merge conflict in this file, just re-run that command — the output is deterministic.
import type { ComponentType } from "react";
import type { FeatureConfig } from "./types";

import config0 from "@/features/attendee-highlights/feature.config";

export const featureConfigs: FeatureConfig[] = [
  config0,
];

export const featureLoaders: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
  "attendee-highlights": () => import("@/features/attendee-highlights"),
};
