name: Deploy Storybook to Vercel

on:
  push:
    branches: [main, develop]
    paths:
      - "src/stories/**"
      - ".storybook/**"
      - "src/components/**/*.stories.*"
      - "tailwind.config.mjs"
      - "src/app/globals.css"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches: [main]
    paths:
      - "src/stories/**"
      - ".storybook/**"
      - "src/components/**/*.stories.*"

  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --local-config=vercel-storybook.json

      - name: Build Storybook
        run: npm run build:storybook

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --local-config=vercel-storybook.json
